project_prompt = '''
- Before beginning work on this feature, write a short haiku.
- When you are done with your task, run format and lint commands
- Do NOT commit your changes.
'''

[commands]
format = ["./run_format.sh"]
test = ["./run_test.sh"]

[git]
auto_commit = false